config/routes.rb
Rails.application.routes.draw do
  root 'toppings#index'
  resources :toppings, only: [:index, :show]
  resources :ice_creams, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/add_on.rb
class AddOn < ActiveRecord::Base
  has_many :toppings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ice_cream.rb
class IceCream < ActiveRecord::Base
  # serialize :categories, Array
  enum course: [:app, :main, :dessert]

  def self.to_csv
    attributes = %w{name servings}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |ice_cream| 
        csv << ice_cream.attributes.values_at(*attributes)
      end
    end
  end
end

app/models/topping.rb
class Topping < ActiveRecord::Base
  belongs_to :add_on

  enum category: [:sweet, :fruity, :savory, :candy]
  enum course: [:app, :main, :dessert]

  def eligible_ice_creams
    IceCream.select do |a|
      a.servings < 30 &&
      a.release_start < release_month &&
      a.release_end > release_month &&
      a.categories.include?(category) &&
      a.course == course
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ice_creams_controller.rb
class IceCreamsController < ApplicationController
  def index
    @ice_creams = IceCream.all

    respond_to do |format|
      format.html
      format.csv { send_data @ice_creams.to_csv }
    end
  end

  def show
    @ice_cream = IceCream.find_by(id: ice_cream_params[:id])
  end

  private

  def ice_cream_params
    params.permit(:id, :name, :release_start, :release_end, :categories, :servings, :course)
  end
end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  def index
    @toppings = Topping.all
  end

  def show
    @topping = Topping.find_by(id: topping_params[:id])
  end

  def create
    @topping = Topping.new(params[:topping])
    @topping.save
  end

  private

  def topping_params
    params.permit(:id, :name, :release_month, :category, :homemade, :course)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ice Cream Selector</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toppings/index.html.erb
<h1>Toppings</h1>
<% @toppings.each do |topping| %>
  <h3><%= topping.name %></h3>
  <p>Category: <%= topping.category %></p>
  <h5><a href='/toppings/<%=topping.id %>'>Show suggested ice creams for <%= topping.name %></a></h5>
<% end %>
<a href="/ice_creams.csv"><button class="btn btn-success">Download CSV of Available IceCreams</button></a>

app/views/toppings/show.html.erb
<h1><%= @topping.name %></h1>
  <h2>from <%= @topping.add_on.name %></h2>

<% if @topping.eligible_ice_creams.empty? %>
  <h3>Sorry, no ice creams match this topping right now!</h3>
<% else %>
  <h3>Suggested Ice Creams:</h3>
  <% @topping.eligible_ice_creams.each do |ice_cream| %>
    <h5>Name:  <%= ice_cream.name %></h5>
    <h5>Release start:  <%= ice_cream.release_start.strftime("%B %d, %Y") %></h5>
    <h5>Release end:  <%= ice_cream.release_end.strftime("%B %d, %Y") %></h5>
    <h5>Categories: <%= ice_cream.categories %></h5>
    <h5>Servings: <%= ice_cream.servings %></h5>
    <h5>Course: <%= ice_cream.course %></h5>
  <% end %>
<% end %>

<%= link_to "Return to Topping List", toppings_path  %>